const Contenedor=require("./brasescoTomasD2.js")

const serviciosProducto=new Contenedor();

let products={}
                                                                                                                                
                                                                                                                                               
                                                                                                                                              
//Llamado de funcionalidades de nuestra clase

  //serviciosProducto.saveProduct(products).then(result=>console.log(result))

  //serviciosProducto.getAll(products).then(result=>console.log(result))

  //serviciosProducto.getById(3).then(result=>console.log(result))

  //serviciosProducto.modifyProduct(1,products).then(result=>console.log(result))

  //serviciosProducto.deleteProduct(3).then(result=>console.log(result))    
  
  
  
  /*, {                                                                                                                                                    
      title: 'Escuadra',                                                                                                                                 
      price: 123.45,                                                                                                                                     
      thumbnail: 'https://cdn3.iconfinder.com/data/icons/education-209/64/ruler-triangle-stationary-school-256.png',                                                                                                                                                                        
    }                                                                                                                                                  
    {                                                                                                                                                    
      title: 'Globo Terráqueo',                                                                                                                          
      price: 345.67,                                                                                                                                     
      thumbnail: 'https://cdn3.iconfinder.com/data/icons/education-209/64/globe-earth-geograhy-planet-school-256.png',                                                                                                                                                                           
    }
    {                                                                                                                                                    
      title: 'Calculadora',                                                                                                                              
      price: 234.56,                                                                                                                                     
      thumbnail: 'https://cdn3.iconfinder.com/data/icons/education-209/64/calculator-math-tool-school-256.png',                                                                                                                                                                                     
    }
 */            